name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: "Run CI"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true
      - name: download assets
        run: make download
      - name: build collector
        run: make collector
      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2023.1.7"
          install-go: false
